site_name: Aidan Steele's blog (usually about AWS)
site_description: Here's my seventh or eighth attempt at a blog. It's mostly going to be my experimentation with using AWS (Amazon Web Services, not Aidan William Steele)
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white 
      accent: black
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: white
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.footer
markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/aidansteele
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/__steele
use_directory_urls: false
plugins:
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - blog: 
      blog_dir: blog
      pagination: true
      post_date_format: full
      post_excerpt: optional
      post_readtime: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
  - search: 
      lang: 
        - en
        - zh
  - tags
