site_name: Aidan Steele's blog (usually about AWS)
site_description: Here's my seventh or eighth attempt at a blog. It's mostly going to be my experimentation with using AWS (Amazon Web Services, not Aidan William Steele)
site_url: https://awsteele.com/
site_author: Aidan W. Steele
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white 
      accent: black
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: white
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.footer
nav: 
  - Blog: blog/index.md
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/aidansteele
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/__steele
    - icon: fontawesome/solid/rss 
      link: /feed_rss_created.xml
extra_css:
  - stylesheets/extra.css
use_directory_urls: false
copyright: By Aidan W. Steele for Mumu, Lulu & Co.
plugins:
  - rss:
      match_path: blog/posts/security/.*
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - categories
        - tags
  - blog: 
      blog_dir: blog
      post_url_format: "{date}/{file}"
      pagination: true
      post_date_format: medium
      post_excerpt: optional
      post_readtime: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
  - search: 
      lang: 
        - en
        - zh
  - tags
