site_name: Aidan Steele's blog (usually about AWS)
theme:
  name: material
  palette:
    primary: white
    - navigation.footer
    - content.code.copy
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
use_directory_urls: false
plugins:
  - rss:
      match_path: blog/category/security/*
      date_from_meta:
        as_creation: date
      categories:
        - categories
  - blog: 
      blog_dir: .
      archive: false
      pagination: false
      post_date_format: full
      post_excerpt: optional
      post_readtime: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
  - search: 
      lang: 
        - en
        - zh
